sudo: true
language: node_js
node_js:
- "5.5"
python:
- "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
  - sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev libwebp-dev
  - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
  - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
  - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm
  - python3 -V
  - pip -V
# command to install dependencies
install:
  - npm install
  - sudo pip install -r requirements/base.txt
  - sudo pip install -r requirements/local.txt
  - sudo pip install -r requirements/production.txt
  - sudo pip install -r requirements/test.txt"
# command to run tests
script:
  - pep8 rapidito
  - flake8 rapidito
  - pylint rapidito
  - pytest
