sudo: true
language: python
python:
- "3.5"
env:
- TRAVIS_NODE_VERSION="7.0.0"
# command to install dependencies
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - pip install -r requirements/base.txt
  - pip install -r requirements/local.txt
  - pip install -r requirements/production.txt
  - pip install -r requirements/test.txt
  - npm install

# command to run tests
script:
  - pep8 rapidito
  - flake8 rapidito
  - pylint rapidito
  - pytest
