sudo: true
language: python
python:
- "3.5"
env:
- TRAVIS_NODE_VERSION="7.0.0"
# command to install dependencies
install:
  - pip install -r requirements/base.txt
  - pip install -r requirements/local.txt
  - pip install -r requirements/production.txt
  - pip install -r requirements/test.txt
  - npm install

# command to run tests
script:
  - pep8 rapidito
  - flake8 rapidito
  - pylint rapidito
  - pytest
