# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorización',
            fields=[
                ('autorización', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Autorizaciones',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.IntegerField()),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('control', models.CharField(max_length=128)),
                ('autorización', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Autorización')),
            ],
        ),
        migrations.AddField(
            model_name='autorización',
            name='nit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Empresa'),
        ),
    ]
