# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorización',
            options={'verbose_name_plural': 'Autorizaciones'},
        ),
        migrations.AlterField(
            model_name='autorización',
            name='autorización',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
